Add Pod Name and Namespace
nimbess/nimbess-cni pull request #6
Opened 2019-08-16 22:04 UTC by trozet

The protobuf in nimbess-agent has changed to allow for the pod name and
namespace to be passed in the CNI request. This is required in order to
annotate the pod with the Fast Path information. This change parses the
pod name and namespace to pass along with the CNI request.

Signed-off-by: Tim Rozet <trozet@redhat.com>

2019-08-17 00:22 UTC, fepan requested changes

2019-08-17 00:22 UTC, fepan commented on cmd/nimbess-cni.go
> +
???

2019-08-19 12:09 UTC, trozet commented on cmd/nimbess-cni.go
> +
will remove

2019-08-19 12:54 UTC, fepan approved these changes

2019-08-19 13:00 UTC, merged